FROM python:3.9-alpine

WORKDIR /app

COPY requirements.txt .

RUN apk update \
    && apk add --virtual build-deps gcc python3-dev musl-dev \
    && apk add --no-cache mariadb-dev
    
RUN python -m pip install --upgrade pip
RUN pip install -r requirements.txt


COPY . .

CMD [ "gunicorn", "-b", "0.0.0.0:5000", "app:app", "--reload" ]